let {getAST,getDependencies,transform} = require('./parser')
const path = require('path')
let ast = getAST(path.join(__dirname, '../src/index.js'))
let deps = getDependencies(ast)
console.log(transform(ast))